[Distribution]
Distribution=kali
Release=kali-rolling
Architecture=arm64

[Output]
Format=disk
Output=kali-rolling
SectorSize=512
CompressOutput=no
SplitArtifacts=

[Content]
Bootable=yes
Autologin=no
Hostname=comet
UnifiedKernelImages=no
Devicetrees=freescale/imx8mp-mecha-comet.dtb
RootPassword=mecha
Environment=DEBIAN_FRONTEND=noninteractive
KernelCommandLine=quiet loglevel=3 audit=0
PostInstallationScripts=mkosi.postinst

Packages=
    apt
    bash
    bash-completion
    bluez
    ca-certificates
    curl
    dbus
    dbus-user-session
    evtest
    htop
    i2c-tools
    iputils-ping
    kali-linux-arm
    libbpf1
    libgpiod-dev
    libnss-systemd
    libpam-modules
    libpam-runtime
    libpam-systemd
    libseccomp2
    login
    net-tools
    passwd
    nano
    git
    openssh-server
    sudo
    systemd
    systemd-boot
    systemd-boot-efi
    systemd-resolved
    upower
    usbutils
    util-linux
    wget    
    xdg-user-dirs

# Custom packages
Packages=
    linux-image-6.12.20+mecha+