[Distribution]
Distribution=fedora
Release=44
Architecture=arm64

[Output]
Format=disk
Output=fedora44
SectorSize=512
CompressOutput=no

[Content]
Bootable=yes
Bootloader=systemd-boot
Autologin=yes
Hostname=comet
UnifiedKernelImages=no
KernelModulesInitrd=no
# Disable mkosi-generated initrd
Initrds=
Devicetree=freescale/imx8mp-mecha-comet.dtb
RootPassword=mecha
PostInstallationScripts=mkosi.postinst

# Include standard groups, they are defined at
# https://pagure.io/fedora-comps/blob/main/f/comps-f43.xml.in

Packages=
    @base-graphical
    @core
    @multimedia
    @networkmanager-submodules
    @standard
    alacritty
    bluez
    cpufrequtils   
    evtest
    greetd
    gsettings-desktop-schemas
    gstreamer
    gstreamer-devel
    htop
    i2c-tools
    impeller
    libgpiod-utils
    libpdfium    
    mechanix-settings
    mechanix-system-service
    mechanix-wallpapers
    mesa-demos
    mpv-devel
    mpv-libs
    mpv
    mutter
    mxconf
    mxsearch
    nano
    openssh-server
    phoc
    phosh
    phosh-mobile-settings
    seatd
    session_service
    sudo
    systemd
    systemd-boot-unsigned
    systemd-pam
    upower
    usbutils
    # vercel-geist-mono-fonts -> only available in testing for Fedora 43
    weston-demo
    xdg-user-dirs
    xorg-x11-server-Xwayland
    # Custom packages
    nxp-firmware-1.0-1.fc43.aarch64
    kernel-7.0.0-2.aarch64
    # libcamera exact versions from Fedora Koji
    https://kojipkgs.fedoraproject.org//packages/libcamera/0.5.2/5.fc43/aarch64/libcamera-0.5.2-5.fc43.aarch64.rpm
    https://kojipkgs.fedoraproject.org//packages/libcamera/0.5.2/5.fc43/aarch64/libcamera-gstreamer-0.5.2-5.fc43.aarch64.rpm
    https://kojipkgs.fedoraproject.org//packages/libcamera/0.5.2/5.fc43/aarch64/libcamera-ipa-0.5.2-5.fc43.aarch64.rpm
