[Distribution]
Distribution=kali
Release=rolling
Architecture=arm64

[Output]
Format=disk
Output=kali-rolling
SectorSize=512
CompressOutput=no

[Content]
Bootable=yes
Autologin=yes
Hostname=comet
UnifiedKernelImages=no
Devicetree=freescale/imx8mp-mecha-comet.dtb
RootPassword=mecha
PostInstallationScripts=mkosi.postinst

Packages=
    bluez
    cpufrequtils
    evtest
    htop
    i2c-tools
    libgpiod-dev
    linux-firmware
    nano
    git
    openssh-server
    sudo
    systemd
    upower
    usbutils
    xdg-user-dirs

# Custom packages
Packages=
    https://github.com/dhruveshb-mecha/linux/releases/download/kernel-deb-latest/linux-image-6.12.20+mecha+_6.12.20-g0248c6c29069-2_arm64.deb
