# Minimal image for testing in QEMU on x86-64
# Selected via `mkosi --profile=qemu build`.

[Output]
Output=mechanix-os-qemu
ImageId=mechanix-os-qemu

[Distribution]
Architecture=x86-64

[Content]

Packages=
    kernel

[Build]
ToolsTreePackages=qemu-ui-sdl

[Runtime]
TPM=no
Console=gui
QemuArgs=-display vnc=:0
CPUs=4
RAM=4G
