# Graphical shell: Wayland compositor, Phosh mobile UI, and terminal/demo apps.

[Content]
Packages=
    @base-graphical
    alacritty
    greetd
    gsettings-desktop-schemas
    mutter
    phoc
    phosh
    phosh-mobile-settings
    # vercel-geist-mono-fonts -> only available in testing for Fedora 43
    weston-demo
    xorg-x11-server-Xwayland
