# Graphical shell: labwc (Wayland compositor), kanshi (output config), wofi
# (app launcher), and terminal/demo apps.

[Content]
Packages=
    @base-graphical
    alacritty
    dejavu-sans-mono-fonts
    greetd
    gsettings-desktop-schemas
    kanshi
    labwc
    mutter
    # vercel-geist-mono-fonts -> only available in testing for Fedora 43
    weston-demo
    wofi
    xorg-x11-server-Xwayland
