hostname: mecha-comet-m
locale:
  timezone: America/Los_Angeles
  lang: en-US.UTF-8
user:
  name: mecha
  password: mecha
  is_password_expired: true
ssh:
  user_ca:
  host_ca:
  authorized_keys: []
  is_password_authentication_disabled: false
debian:
  version: 12
  name: bookworm
apt:
  sources:
os-release:
  ID: mechanix
  ID_LIKE:
    - debian
  NAME: Mechanix
  VERSION: "24.03.0 LTS (Apollo)"
  VERSION_ID: "24.03"
  VERSION_CODENAME: Apollo
  PRETTY_NAME: "Mechanix 24.03 LTS"
  HOME_URL: "https://mecha.so/"
  SUPPORT_URL: "https://forum.mecha.so/"
  BUG_REPORT_URL: "https://forum.mecha.so/"
packages-path: /home/jack/Desktop/mecha/mecha-make/temp/build-debian/include/packages
scripts-path:   /home/jack/Desktop/mecha/mecha-make/debian/include/scripts/
media-files : /home/jack/Desktop/mecha/mecha-make/build-debian/include/media-files
firmware-files : /home/jack/Desktop/mecha/mecha-make/debian/include/packages/firmware
