name: Fedora Build

on:
  push:
    branches:
      - main
      - dev*
    paths:
      - fedora/distro/**
      - .github/workflows/fedora-build.yml

  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  build:
    strategy:
      matrix:
        machine: [mecha-comet-gen1]
    runs-on: ubuntu-22.04
    container:
      image: fedora:42
    steps:
      - name: Install dependencies
        run: |
          dnf -y update
          dnf -y install sudo curl git rsync cpio @development-tools bc make gcc elfutils-libelf-devel openssl-devel flex bison dwarves ncurses-devel cpio rsync openssl-devel-engine rpm-build rpmdevtools dwarves openssl perl

      - name: Install Docker Engine from RPM repository
        run: |
          sudo dnf -y install dnf-plugins-core
          sudo dnf3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
          sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo systemctl enable --now docker
          sudo usermod -aG docker $USER
          newgrp docker
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug - List contents of debian directory
        run: |
          ls -R debian/packages

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: debian/distro.Dockerfile
          push: false
          load: true
          tags: mechasystems/distro:latest

      - name: Debug - List Docker images
        run: docker images

      - name: Debug - Show Docker image details
        run: docker inspect mechasystems/distro:latest

      - name: Remove existing container if it exists
        run: |
          docker rm -f distro-container || true

      - name: Make artifacts directory
        run: mkdir -p artifacts

      - name: Run Docker container and collect artifacts
        run: |
          docker run --name distro-container mechasystems/distro:latest
          docker ps -a
          docker logs distro-container
          docker cp distro-container:/build/assets/deploy/fedora-image-rootfs.tar.gz ./artifacts || echo "Failed to copy artifacts"

      - name: Debug - List container filesystem
        if: failure()
        run: |
          docker exec distro-container ls -R /

      - name: list artifacts
        run: |
          ls -R ./artifacts || echo "No artifacts found"

      - name: Clean up
        if: always()
        run: |
          docker stop distro-container || true
          docker rm distro-container || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fedora-image-rootfs.tar.gz
          path: ./artifacts/*
